name: Create Release PR
on:
  push:
    branches:
      - 'release/*'  # リリースブランチが作成されたらトリガー

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get release branch name
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Get list of PRs to be merged
        id: pr-list
        run: |
          prs=$(gh pr list --base main --head ${{ env.branch_name }} --json number,title,body,htmlUrl)
          echo "$prs" > prs.json
          echo "prs=$(jq -r '.[] | "- \(.htmlUrl)"' prs.json)" >> $GITHUB_ENV

      - name: Extract ticket URLs from PR descriptions
        id: ticket-list
        run: |
          tickets=$(jq -r '.[] | .body | capture("(https?://[\\w./-]+)")? | select(. != null) | .string' prs.json | sort -u)
          echo "$tickets" > tickets.txt
          echo "tickets=$(cat tickets.txt | sed 's/^/- /')" >> $GITHUB_ENV

      - name: Create release PR
        uses: actions/github-script@v6
        with:
          script: |
            const { date, branch_name, prs, tickets } = process.env;
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Release] ${branch_name}`,
              head: branch_name,
              base: 'main',
              body: `
              # 概要
              ${date} リリースブランチ

              # チケットへのリンク
              ${tickets}

              # 変更点
              ${prs}
              `
            });
