name: Create Release Branch and PR

on:
  workflow_dispatch: # 手動実行のみ

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      # リポジトリを全履歴でチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Gitユーザー情報を設定
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 日付情報からリリースブランチ名・PRタイトル用文字列を生成
      - name: Generate branch name
        id: date
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "year_month=$(date +'%Y年%m月')" >> $GITHUB_OUTPUT

      # developからリリースブランチを作成してpush
      - name: Create release branch
        run: |
          git fetch origin
          git checkout develop
          git pull
          BRANCH_NAME="release/${{ steps.date.outputs.date }}"
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "既にリリースブランチ $BRANCH_NAME が存在するため作成をスキップします。"
          else
            git checkout -b $BRANCH_NAME
            git push origin $BRANCH_NAME
          fi

      # GitHub CLIとjqをインストール
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh jq

      # mainからdevelopまでのPR番号一覧を取得
      - name: Collect merged PR numbers
        id: prs
        run: |
          prs=$(git log --merges --pretty=format:"%s" origin/main..origin/develop | grep -E 'Merge pull request' | sed -E 's/Merge pull request #([0-9]+) from .*/\1/')
          echo "prs<<EOF" >> $GITHUB_OUTPUT
          echo "$prs" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      # mainからdevelopまでのPR番号一覧を取得（src/BusForecast.Database配下の変更があるPRのみ抽出）
      - name: Collect merged PR numbers (Database only)
        id: prs_database
        run: |
          dbprs=""
          for sha in $(git log --merges --pretty=format:"%H" origin/main..origin/develop); do
            files=$(git show -m --name-only --pretty="" $sha 2>/dev/null) || true
            # Database配下のファイル変更があるか判定
            if echo "$files" | grep -q "^src/DB/"; then
              pr=$(git log -1 --pretty=format:"%s" $sha | grep -oE 'Merge pull request #[0-9]+' | grep -oE '[0-9]+')
              if [ -n "$pr" ]; then
                dbprs="$dbprs* https://github.com/${{ github.repository }}/pull/$pr\n"
              fi
            fi
          done
          echo "prs_database<<EOF" >> $GITHUB_OUTPUT
          echo -e "$dbprs" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 発行対象プロジェクト一覧を判定
      - name: Determine build targets
        id: determine-build
        shell: pwsh
        run: |
          # プロジェクト定義リスト
          $projects = @(
            @{ name = "Aアプリ"; path = @("src/A", "src/B"); workflow = "A_stg_publish.yml" },
            # @{ name = "Bアプリ"; path = @("src/B"); workflow = "B_stg_publish.yml" },
            @{ name = "Cアプリ"; path = @("src/C"); workflow = "C_stg_publish.yml" }
          )
          # developとの差分ファイルから対象プロジェクト抽出
          $changedFiles = git diff --name-only origin/main HEAD
          $targets = @()
          foreach ($project in $projects) {
            foreach ($p in $project.path) {
              if ($changedFiles | Where-Object { $_ -match "$p/*" }) {
                if (-not ($targets | Where-Object { $_.name -eq $project.name })) {
                  $targets += $project
                  break
                }
              }
            }
          }
          # JSON化して環境変数に格納
          $targetsJson = $targets | ConvertTo-Json -Compress
          "BUILD_TARGETS=$targetsJson" | Out-File -FilePath $env:GITHUB_ENV -Append

      # PR本文生成（対象プロジェクト一覧＋workflow_dispatchボタン）
      - name: Create PR
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $targets = $env:BUILD_TARGETS | ConvertFrom-Json
          $projectList = ""
          foreach ($t in $targets) {
            $workflowUrl = "https://github.com/${{ github.repository }}/actions/workflows/$($t.workflow)"
            $projectList += "* $($t.name) [ステージング発行]($workflowUrl)`n"
          }
          $title = "${{ steps.date.outputs.year_month }}リリース"
          $prList = ""
          foreach ($line in ("${{ steps.prs.outputs.prs }}" -split "`n")) {
            if ($line -match '(\d+)') {
              $prNum = $matches[1]
              $prUrl = "* https://github.com/${{ github.repository }}/pull/$prNum"
              $prList += "$prUrl`n"
            }
          }
          $dbList = "${{ steps.prs_database.outputs.prs_database }}"
          $body = "## 概要`n${{ steps.date.outputs.year_month }}リリース`n## チケットへのリンク`n* `n## リリースに含まれる変更:`n`n$prList`n## DB変更内容`n$dbList`n## 発行対象プロジェクト`n$projectList"
          gh pr create --base main --head release/${{ steps.date.outputs.date }} --title "$title" --body "$body"