name: .NET Core

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: latest 
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --output .\artifacts --configuration Release
    - name: Add TestPack Source
      run: nuget sources Add -Name "TestPack" -Source https://nuget.pkg.github.com/GCnaoto/index.json -UserName GCnaoto -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: nuget push ".\artifacts\" -Source "TestPack" -SkipDuplicate 
