name: リリースPR作成

on:
  push:
    branches:
      - 'release/*'  # リリースブランチが作成されたときにトリガー

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # リリースブランチをmainブランチにマージするPRを作成するため、リモートを更新
    - name: Fetch all branches
      run: git fetch --all

    # 現在のリリースブランチ名を取得
    - name: Get release branch name
      run: echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    # マージされていないPRを取得
    - name: Get merged PRs
      id: get_prs
      run: |
        PR_LIST=$(git log --merges --pretty=format:"%s" origin/${{ env.RELEASE_BRANCH }} --not origin/main)
        echo "PR_LIST=${PR_LIST}" >> $GITHUB_ENV

    # 各PRの説明にあるチケットURLを抽出
    - name: Extract ticket URLs from PRs
      id: extract_tickets
      run: |
        TICKET_URLS=""
        for pr in $(git log --merges --pretty=format:"%s" origin/${{ env.RELEASE_BRANCH }} --not origin/main); do
          if [[ $pr =~ (https?://[^\ ]+) ]]; then
            TICKET_URLS+="${BASH_REMATCH[1]}\n"
          fi
        done
        echo "TICKET_URLS=${TICKET_URLS}" >> $GITHUB_ENV

    # 日付を取得
    - name: Get current date
      id: date
      run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # PRを作成
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: ${{ env.RELEASE_BRANCH }}
        title: 'Release: ${{ env.RELEASE_BRANCH }}'
        body: |
          # 概要
          ${{ steps.date.outputs.current_date }}リリースブランチ
          
          # チケットへのリンク
          ${{ env.TICKET_URLS }}
          
          # 変更点
          プルリクエスト一覧
          ${{ env.PR_LIST }}
